### ISSUE TITLE
Caused by 0: java.lang.reflect.InvocationTargetException Crash

### ISSUE THREAD

**Issue by YukiRainee** [oierbravo/createsifter#11]
Both Create Sifter and GraphUtil have this crash error hoping its not something else but hopefully this gets solved
[crash-2022-12-19_20.35.59-fml.txt](https://github.com/oierbravo/createsifter/files/10265443/crash-2022-12-19_20.35.59-fml.txt)

**Comment by oierbravo** [comment]
Hi!
You need to use latest [createsifter-1.19.2-1.3.2.g.jar](https://www.curseforge.com/minecraft/mc-mods/create-sifting/files/4175752) version with create 0.5.g
