### ISSUE TITLE
[1.18] [1.3.3.g] [Bug] Tags in custom recipes not working

### ISSUE THREAD

**Issue by Filostorm** [oierbravo/createsifter#12]
After the update to Create.g, tags in custom recipes stopped working. They display as empty tag items. This is using the shipped KubeJS support.

I also started using the default methods, rather then a custom method, so that could be the cause as well. However, the default methods working for tags would be appreciated. 

Thanks!

**Comment by oierbravo** [comment]
Hi!
Thanks for the report!
Tags are driving me mad! XD event in datapack recipes.
I'm looking to solve the problem.
