### ISSUE TITLE
[Suggestion]: Support for "Ex Nihilo: Sequentia" Meshes

### ISSUE THREAD

**Issue by PercyCreeper** [oierbravo/createsifter#14]
I would really love if you could add support for the Meshes of the current Ex Nihilo: Sequentia mod, as your mod and theirs would both fit into a modpack, but  currently you need to use different meshes in order to use the different sieves from the different mods... Having a solution where you could just use the meshes of one mod for both mods would be very handy :)

**Comment by oierbravo** [comment]
Hi!
Thanks for the suggestion!
I'm working on it... but I think I have to rewrite some parts to make it happen.

**Comment by PercyCreeper** [comment]
Thanks for working on it :) I would make my own mod to create meshes that work for both, but thet also doesnt seem to possible/ that easy, as for both of you the block checks for an instance of a specific class that basically is your own base mesh xD

**Comment by AlwaysReadyWBY** [comment]
I managed to generate a datapack for Ex Nihilo Sequentia recipes. So what should I do about the Meshes?

**Comment by NightOps007** [comment]
Aren't Ex Nihilo meshes enchantable? Would that create issues with the sifter or is that a feature be adapted to this mod as well?
