### ISSUE TITLE
[Suggestion] Visual representation of the block being sieved

### ISSUE THREAD

**Issue by PercyCreeper** [oierbravo/createsifter#16]
This is just a visual suggestion, so it isn´t as important to me, but I would like to see visually, which block is being sieved by the autosifter, maybe also in the way Ex Nihilo did it with their sieves, so you can see the block slowly going down through the mesh of the sieve. 
It would just add a bit to the atmosphere :)

**Comment by oierbravo** [comment]
Hi!
Thanks for the suggestion!
It's already in the list :)

**Comment by PercyCreeper** [comment]
Nice :)
