### ISSUE TITLE
Difficulty with Custom Mesh

### ISSUE THREAD

**Issue by ClaudiusMinimus** [oierbravo/createsifter#19]
I am having difficulty getting my custom mesh to render correctly. The mesh processes my recipes just fine, though I would like for it to look correct as well. I also want to add a couple more meshes, but would like to get this one right before I do.

Thank you and I appreciate your help!

Details listed below:

- Minecraft: 1.19.2
- Forge: 43.2.3
- Create: 1.19.2-0.5.0.h
- Create Sifter 1.19.2-1.3.3.g

**This what the mesh is supposed to look like from BlockBench.**
![image](https://user-images.githubusercontent.com/17887664/216657802-3f0923ff-706e-42f1-8726-0922dd8b32b1.png)

**This is how it renders in game**
![image](https://user-images.githubusercontent.com/17887664/216666057-c66f2b6a-e58e-474a-8485-0239c53684e0.png)

In order to get the mesh to work and render as well as it does I had to do the following:
1. In BlockBench, create the `kubejs/assets/createsifter/models/block/meshes/amethyst_mesh.json`
2. In BlockBench, create, edit and apply the textures found in `kubejs/assets/createsifter/textures`
3. Copy  `kubejs/assets/createsifter/textures` to `kubejs/assets/kubejs/textures`

**Attached are the pertinent files [kubejs.zip](https://github.com/oierbravo/createsifter/files/10581328/kubejs.zip)**

![image](https://user-images.githubusercontent.com/17887664/216667899-8a5a9ada-a2a3-40f4-a139-5adfaea64bf1.png)

**Comment by ClaudiusMinimus** [comment]
Also, do you have a discord server that you could invite me to?

**Comment by oierbravo** [comment]
Hi!
I've updated the mod to patch I and fixed rendering issues.
I think your problem may be resolved.

**Comment by ClaudiusMinimus** [comment]
Definitely a set in the right direction!
Would be nice if they were rotated to the same plane as the sifter.  :smile: 
Also, the border frame as shown in the above BlockBench example still needs rendering.
Thank you very much for working on this!
![image](https://user-images.githubusercontent.com/17887664/216777670-01273c26-3de1-4f51-8e1a-6f7f545967b6.png)

**Comment by oierbravo** [comment]
Hi!
I'm reworking the models and doc to simplify the process.
In the meantime... could you try please:
```

StartupEvents.registry('item', event => {
	// Register new items here
	// event.create('example_item').displayName('Example Item')
	event.create('amethyst_mesh','createsifter:mesh').displayName('Amethyst Mesh').parentModel("createsifter:block/meshes/custom_mesh").texture("1","kubejs:item/amethyst_mesh").texture("0","kubejs:block/coal_block");
})
```
It just adds the custom model and texture overrides.

**Comment by ClaudiusMinimus** [comment]
Looks GREAT!
Thanks! I look forward to the update!
![image](https://user-images.githubusercontent.com/17887664/216984785-d96d7293-0426-4b5d-83de-69722e26c84d.png)
