### ISSUE TITLE
Not Compatible with Create .5.1.a Update

### ISSUE THREAD

**Issue by ClaudiusMinimus** [oierbravo/createsifter#29]
Create Sifter version `createsifter-1.19.2-1.4.0.i.jar` is not compatible with the new Create .5.1.a update.

![image](https://github.com/oierbravo/createsifter/assets/17887664/e492e32f-5707-4ace-8b53-88e0ddca07b1)

**Comment by skellitor301** [comment]
Can confirm, posting to bump.

**Comment by YokoSilver** [comment]
Can also confirm, was met with _Mod createsifter requires create 0.5.0i or above, and below 0.51_ as the error message. Hoping this and many other create mods get updated soon.

**Comment by oierbravo** [comment]
Done!

**Comment by MSandro** [comment]
same for Fabric Version, still not fixed
