### ISSUE TITLE
[1.19.2] Missing nugget output on Gravel Brass Mesh Recipe

### ISSUE THREAD

**Issue by ffuentesm** [oierbravo/createsifter#31]
Create: 0.5.1b
Sifter: 1.19.2-1.5.1.b-30

While other gravel outputs have the nuggets, Brass is missing those on JEI, even though it has the slots showing it outputs something. 
![image](https://github.com/oierbravo/createsifter/assets/44974827/311ad45c-0014-4a7b-949b-b8726e1f3b96)

**Comment by Dr-WeiAL** [comment]
This problem is caused by the fact that Create changed the item id but Create Sifting did not follow the change
create:crushed_copper_ore -> create:crushed_raw_copper

Have to wait for Create Sifting to fix it
