### ISSUE TITLE
[Suggestions] Out-of-the-box functionality for skyblock

### ISSUE THREAD

**Issue by NightOps007** [oierbravo/createsifter#33]
# Skyblock Ready!
  I really want to try doing skyblock with this, but it needs some improvements first. Yes, it's nice that we can add are own recipes and meshes, but very few people are willing to actually do that(myself included, obviously). I've been **sifting** through sourceforge for like three days now trying to plug the holes with other small, not too game changing mods and I'm still not quite there. It would definitely increase the number of downloads if this could be used for skyblock as is with just vanilla+create mod. Just me, a tiny dirt platform with water flowing over the side and a single oak sapling.
- Plant seeds/saplings should be siftable with dirt and a string mesh(not waterlogged).
- P.S. Coral can be bonemealed from sand with water on top so long as your in a warm ocean biome. It's not necessary to make it available from sifting. The kelp is good though and maybe add a pickle?
- And STOP! I just started, so where did I get the string? Spiders are scary and s'not like we got some silkworms lying around or anything. Also, why must the first mesh always be string? A wicker mesh would be much more durable and could be made from just sticks(possibly a 9x9 grid of them in the crafting table).
- Add a way to get the basic stones at the start: cobble/andesite. How can I get anything except the ~~string~~ wicker mesh without it? Could take a page from ex nihilo and get pebbles from sifting dirt.
- Seriously, I just used up all my spare dirt, need more but how do we get it? Maybe by mulching instead of composting...block made of wood with similar mechanic, but will produce dirt?
- Ok, I got some cobble at this point, Now how do I turn it into gravel so I can hand sift it? Maybe we should ~~steal~~ borrow from ex nihilo again and use a hammer?
- I found that there isn't any issue with getting to the nether. So long as the above is solved anyways. Just wash magma blocks to get obsidian. Ingredients for magma creams can be gotten from other processes.
- Now that I'm in the nether, I recalled that I absolutely **hate** searching for ancient debris and netherite scraps. Possibly add a netherite mesh that has a small chance of getting it?
- Add diamond, emerald, amethyst and prismarine to sifting recipes too. Or add a rock tumbler machine to get the shinies from? <-- I feel like this would be a really great addition to this mod. Just make it require lots of SU and have an expensiv-ish/complex mechanical crafting recipe.

## Illogic Puzzle?
  I'm having a migraine trying to wrap my head around the logic of how the zinc mesh is better than the andesite one. FYI zinc is softer than copper and would make a terrible mesh IRL. And zinc or iron nuggets are needed to make the andesite alloy the mesh is made with. Could the andesite and zinc positions be swapped? Or maybe just use andesite, not the alloy, to make it?

**Comment by ClaudiusMinimus** [comment]
@NightOps007 I have added many of the things mentioned in my pack, [Create on a Potato PC: Ultimate](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato). I have even added some custom meshes, though with the Create 0.5.1 update, the [mesh textures are broken](https://github.com/oierbravo/createsifter/issues/32). You are welcome to look at what I have done to implement your own changes.

**Comment by geniusogonek** [comment]
I got interested in the mod and wanted to add custom crafts. I also survive skyblock and wanted to add more mods, but skyblock survival doesn't allow me to use these mods. I also tried to add custom craft by changing the mod files, but nothing worked, neither adding a new craft, nor even changing the sifting time, or anything like that. I really look forward to the opportunity to create my crafts, thanks for the post, you wrote it instead of me :)

**Comment by ClaudiusMinimus** [comment]
@ogone4ek2090 Feel free to take a look at my examples:
- [Custom Mesh](https://github.com/ClaudiusMinimus/CreatePotatoUltimate/tree/main/minecraft/kubejs/data/createsifter) (textures are still broken)
- [Custom Recipes](https://github.com/ClaudiusMinimus/CreatePotatoUltimate/tree/main/minecraft/kubejs/data/createsifter/recipes/sifting)

I hope these examples help!
