### ISSUE TITLE
Kubejs custom mesh renders incorrectly on the sifter

### ISSUE THREAD

**Issue by DragonMaster14545** [oierbravo/createsifter#34]
I made a custom mesh with kubejs, it works fine but when I put it onto the sifter, the texture is weird. This is my code: event.create('citrine_mesh','createsifter:mesh').displayName('Citrine mesh').texture('kubejs:item/custom_mesh').color(0, 0xFFA500)
the custom mesh texture is just the string mesh texture from your mod because it is white wich means I can be lazy and use .color(). Kubejs and create sifter mod are the newest verions for 1.19.2.
Thanks in advance
![Uploading Screenshot (199).png…]()

**Comment by ClaudiusMinimus** [comment]
This sounds like it is related to my issue as well https://github.com/oierbravo/createsifter/issues/32

**Comment by DragonMaster14545** [comment]
Seams so yes

**Comment by ClaudiusMinimus** [comment]
Is this project still active?

**Comment by oierbravo** [comment]
Yes! if you have doubts you can always look at the commits.

**Comment by oierbravo** [comment]
Updated Readme for custom meshes.

**Comment by ClaudiusMinimus** [comment]
Oh sorry, I've not been feeling well when I saw this https://github.com/oierbravo/createsifter/issues/34#issuecomment-1659399069 in my email inbox. I see you are working on it still. Thank you!
