### ISSUE TITLE
Fixed the texture after Create 0.5.1

### ISSUE THREAD

**Issue by Pixl64** [oierbravo/createsifter#35]
Due to the texture changes in the latest version of create, there were some issues with the textures, as the positions of the model files had changed.

I'm not very good at using GitHub, so I don't know how pull requests work, as I understand that would have been the better idea, but I fixed them and attached them to this issue (they are in txt format as GitHub doesn't allow JSON upload)

[block.txt](https://github.com/oierbravo/createsifter/files/12008721/block.txt)
[inner.txt](https://github.com/oierbravo/createsifter/files/12008722/inner.txt)
[item.txt](https://github.com/oierbravo/createsifter/files/12008723/item.txt)

**Comment by ClaudiusMinimus** [comment]
> I'm not very good at using GitHub, so I don't know how pull requests work, as I understand that would have been the better idea

@Pixl64 [GitHub Desktop](https://desktop.github.com/) is an easy way to get started with git. There are lots of videos showing you how to use it as well.

**Comment by Pixl64** [comment]
Thanks, I think I worked out how to do it
