### ISSUE TITLE
[1.19.2] Breaks with KubeJS as of 1902.6.1

### ISSUE THREAD

**Issue by Xetaxheb** [oierbravo/createsifter#37]
KubeJS will not load as of .1-300 or .1-305, 1902.6.0-142 still loads fine.

**Comment by DragonMaster14545** [comment]
Same issue here, kubejs updated the api for addon devs, please fix this as quick as possible as it keeps me from plaing

**Comment by DragonMaster14545** [comment]
Thanks for the update

**Comment by oierbravo** [comment]
@Dracks2002  can you plz send the StartScript causing the problem and the full log can be helpfull too.

**Comment by oierbravo** [comment]
[KubeJS-Create](https://www.curseforge.com/minecraft/mc-mods/kubejs-create) is required for KJS 6.1

**Comment by Dracks2002** [comment]
[startup.log](https://github.com/oierbravo/createsifter/files/12165396/startup.log)
