### ISSUE TITLE
KubeJS Thread

### ISSUE THREAD

**Issue by KingTino104** [oierbravo/createsifter#42]
### Describe the Suggestion

This is a thread about how i dont understand KubeJS.

**Comment by oierbravo** [comment]
The doc is for pack developer with previous knowledge in KubeJS, datapack and/or CraftTweaker.
Can you be more specific so I can address the issue.

**Comment by billjk2013** [comment]
Alternatively, if you need a code that has been implemented look in the kubejs folder of ftbskies

**Comment by KingTino104** [comment]
> Alternatively, if you need a code that has been implemented look in the kubejs folder of ftbskies

... welp i tried 'copying' those recipes it didnt work 

note: i did fix all mods that arent in my pack so

**Comment by KingTino104** [comment]
here is the error im getting
![image](https://github.com/oierbravo/createsifter/assets/90916297/cb9ee0c0-9d0b-410a-8acd-89f78bc25f5c)

**Comment by billjk2013** [comment]
The spores are a default mincraft item not exnihilo

**Comment by KingTino104** [comment]
> here is the error im getting ![image](https://user-images.githubusercontent.com/90916297/271845547-cb9ee0c0-9d0b-410a-8acd-89f78bc25f5c.png)

if u need modlist lmk

**Comment by billjk2013** [comment]
Download crafttweaker and make sure that the item ID are correct by going to creative and put the item in you hand then I chat type /ct hand

**Comment by KingTino104** [comment]
ok btw i have crafttweaker i just havnet used it since i saw kubejs was released for 1.20

btw i saw ur message about mycelium spores i know but i also said that it was kubejs thing so

![image](https://github.com/oierbravo/createsifter/assets/90916297/cdb9c24e-785d-4bc8-9d96-8635f8b08ef7)

**Comment by billjk2013** [comment]
I wouldn't be able to do anything with it for about 8 hours but I could give it a go after I'm off work

**Comment by KingTino104** [comment]
> but I could give it a go after

k btw i will be asleep in 8 hours so i will not be able to respond.

**Comment by billjk2013** [comment]
For example I think famersdelights may need to be famers_delights

**Comment by KingTino104** [comment]
its a problem with the script but u said copy from ftbskies thats what i did
so like the problem isnt anything with items btw in screenshot u can see that it isnt the problem.

oh btw @oierbravo why dont u tell me something, u said theres nothing to fix. i could've done it myself  but ur docs arent good enough only thing i need is the crafting type or somtehing idk what its called so

**Comment by KingTino104** [comment]
Also this is what i was talking about fix your readme:

@oierbravo 

the first thing about sifting recipes 
it dosent say kubejs or something, it just says sifting recipes.
If that is for a datapack you could've said like datapack format or something, u shouldn't just say sifting recipes.
Also you need to make it more obvious what is for kubejs 5 and what is for kubejs 6.

**Comment by KingTino104** [comment]
@billjk2013 i think i might have an idea what could be the problem.

![image](https://github.com/oierbravo/createsifter/assets/90916297/ab2f3b28-9e06-499c-8e79-c25caef6d5cb)

**Comment by billjk2013** [comment]
Possibly I was using 6.3 but I'm working on 1.20.1

**Comment by KingTino104** [comment]
yea im working on 1.20 too

**Comment by KingTino104** [comment]
thats the only thing that could be a problem tho

**Comment by billjk2013** [comment]
Possibly

**Comment by KingTino104** [comment]
> Possibly

visual studio code says no errors, im gonna try using a datapack now.

**Comment by KingTino104** [comment]
thanks,
i used a datapack

**Comment by billjk2013** [comment]
after about a year (most of it with out working on my mod pack) `I` figured it out`` here's my first working example
```
ServerEvents.recipes(event => {
    event.recipes.createsifter.sifting({
        type: "createsifter:sifting",
        ingredients: [
            {
                item: "createsifter:string_mesh"
            },
            {
                item: "minecraft:gravel"
            }
        ],
        results: [
            {
                item: "exdeorum:aluminum_ore_chunk",
                chance: 0.08
            },
            {
                item: "minecraft:amethyst_shard",
                chance: 0.02
            },
            {
                item: "exdeorum:boron_ore_chunk",
                chance: 0.06
            },
            {
                item: "minecraft:coal",
                chance: 0.2
            },
            {
                item: "exdeorum:copper_ore_chunk",
                chance: 0.16
            },
            {
                item: "minecraft:diamond",
                chance: 0.04
            },
            {
                item: "minecraft:emerald",
                chance: 0.02
            },
            {
                item: "minecraft:flint",
                chance: 0.4
            },
            {
                item: "exdeorum:gold_ore_chunk",
                chance: 0.06
            },
            {
                item: "exdeorum:iridium_ore_chunk",
                chance: 0.06
            },
            {
                item: "exdeorum:iron_ore_chunk",  // Fixed typo here
                chance: 0.2
            },
            {
                item: "minecraft:lapis_lazuli",
                chance: 0.06
            },
            {
                item: "exdeorum:lead_ore_chunk",  // Fixed typo here
                chance: 0.08
            },
            {
                item: "exdeorum:magnesium_ore_chunk",
                chance: 0.14
            }
        ],
        processingTime: 500
    });
});
```
