### ISSUE TITLE
custom mesh adition

### ISSUE THREAD

**Issue by billjk2013** [oierbravo/createsifter#43]
### Describe the Bug

i keep getting a start up error when trying to add custom meshes

### Reproduction Steps

1.download scripts form https://github.com/carbon-kjs/create-sifting
2.make name changes to scripts and asset folder to match mod pack's name
3.start games
4.errors
...

### Expected Result

the custom meshes would be added to the game and it would load to main menue

### Screenshots and Videos

![start up code](https://github.com/oierbravo/createsifter/assets/133094322/22684a15-981c-43a1-95c1-a3e76208834e)
![startup scrip errror](https://github.com/oierbravo/createsifter/assets/133094322/2eccc2b6-7e1c-444c-abe7-4abd9065caff)
![texture location](https://github.com/oierbravo/createsifter/assets/133094322/026e5c97-b05f-40f0-908c-6a6bba44a45e)

### Crash Report or Log

https://github.com/billjk2013/error-log

### Operating System

windows10

### Mod Version

1.7.4.d-9

### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Other Mods

Ad-Astra-Giselle-Addon-forge-1.20.1-5.6.jar
AdditionalEnchantedMiner-1.20.1-1201.0.17.jar
ad_astra-forge-1.20.1-1.15.3.jar
ae2wtlib-15.0.11-forge.jar
Apotheosis-1.20.1-7.0.5.jar
ApothicAttributes-1.20.1-1.1.4.jar
appliedenergistics2-forge-15.0.11.jar
architectury-9.1.12-forge.jar
ars_nouveau-1.20.1-4.4.0-all.jar
balancedflight-1.20.1_v2.1.0.jar
balm-forge-1.20.1-7.1.4.jar
bellsandwhistles-0.1-1.20.1.jar
biggerreactors-1.20.1-0.6.0-beta.10.1.jar
BiomesOPlenty-1.20.1-18.0.0.597.jar
biomimicry-0.2b-release.jar
Bookshelf-Forge-1.20.1-20.0.5.jar
BotanyPots-Forge-1.20.1-13.0.16.jar
BotanyPotsTiers-Forge-1.20.1-6.0.0.jar
BotanyTrees-Forge-1.20.1-9.0.7.jar
botarium-forge-1.20.1-2.2.0.jar
buildinggadgets2-1.0.1.jar
cloth-config-11.1.106-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
collective-1.20.1-6.66.jar
comforts-forge-6.3.3+1.20.1.jar
compact_storage_forge-5.1.2-1.20.1.jar
configuration-forge-1.20.1-2.2.1.jar
CookedApple-1.20.1.jar
cosmeticarmorreworked-1.20.1-v1a.jar
crafting-on-a-stick-1.20.1-1.0.2.jar
CraftTweaker-forge-1.20.1-14.0.17.jar
create-1.20.1-0.5.1.d.jar
create-confectionery1.20.1_v1.0.9.jar
Create-Guardian-Beam-Defense-1.2.9b-1.20.1.jar
create-new-age-forge-1.20.1-1.0.1.jar
create-structures-0.1.1-1.20.1-FORGE.jar
create-stuff-additions1.20.1_v2.0.4a.jar
createaddition-1.20.1-1.1.0.jar
createbigcannons-forge-1.20.1-0.5.2.a.jar
CreateCasing-1.20.1-1.4.2.jar
createcherry-0.4-1.20.1.jar
createchunkloading-1.6.0-forge.jar
createdieselgenerators-1.20.1-1.1d.jar
CreateDrinks-1.0.2-1.20.1.jar
createeditions-1.0.1+1.20.1_forge.jar
createendertransmission-2.0.4-1.20.1.jar
createliquidfuel-2.0.2-1.20.1.jar
createmoredrillheads-2.0.2-1.20.1.jar
createoreexcavation-1.20-1.4.0.jar
createsifter-1.20.1-1.7.4.d-9.jar
createutilities-0.1.3+1.20.1.jar
create_compressed_1.0.1_forge_1.20.1.jar
Create_Deco_Casing_3.0.0_1.20.1.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.d-1.2.6.c.jar
create_haven-0.0.3-1.20.1.jar
create_jetpack-forge-4.0.2.jar
create_mechanical_extruder-1.20.1-1.5.6.d-9.jar
create_mechanical_spawner-1.20.1-0.0.13.d-9.jar
create_misc_and_things_ 1.20.1_4.0A.jar
create_recycle_1.0.2_forge_1.20.1.jar
create_trains_on_trains-1.0.0.jar
curios-forge-5.3.2+1.20.1.jar
Cyclic-1.20.1-1.12.4.jar
dummmmmmy-1.20-1.8.3.jar
easy_villagers-1.20.1-1.0.12.jar
elevatorid-1.20.1-1.8.15.jar
enderchests-forge-1.20.1-1.1.jar
endertanks-forge-1.20.1-1.1.jar
eureka-1201-1.3.0-beta.2.jar
exdeorum-1.5.jar
extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar
extendedseating-0.1-1.20.1.jar
extremesoundmuffler-3.39-forge-1.20.jar
fabulous_flowers-1.1.0[forge-1.20.1].jar
FarmersDelight-1.20.1-1.2.3.jar
FastLeafDecay-31.jar
flib-1.20.1-0.0.11.jar
FlowerSeeds2-1.20.1-1.0.1.jar
FlowerSeeds2BiomesOPlenty-1.20.1-1.0.1.jar
FlowerSeeds2Cyclic-1.20.1-1.0.1.jar
FlowerSeeds2FabulousFlowers-1.20.1-1.0.1.jar
FlowerSeeds2Roses-1.20.1-1.0.1.jar
FluxNetworks-1.20.1-7.2.0.14.jar
forgivingvoid-forge-1.20-10.0.0.jar
ftb-library-forge-2001.1.3.jar
ftb-ultimine-forge-2001.1.2.jar
ftb-xmod-compat-forge-2.0.1.jar
ftbbackups2-forge-1.20-1.0.19.jar
fusion-1.0.5a-forge-mc1.20.jar
geckolib-forge-1.20.1-4.2.3.jar
HostileNeuralNetworks-1.20.1-5.1.3.jar
item-filters-forge-2001.1.0-build.55.jar
jei-1.20.1-forge-15.2.0.27.jar
JustMoreCakes-forge-1.20.1-1.13.1.jar
kotlinforforge-4.4.0-all.jar
kubejs-forge-2001.6.3-build.45.jar
lbac release 1.20.1 2.jar
LibX-1.20.1-5.0.5.jar
macawsbridgesbop-1.20-1.1.jar
macawsroofsbop-1.20-1.0.jar
mcjtylib-1.20-8.0.3.jar
mcw-bridges-2.1.1-mc1.20.1forge.jar
mcw-fences-1.0.7-mc1.20.1forge.jar
mcw-roofs-2.2.4b-mc1.20.1forge.jar
mcwfencesbop-1.20-1.0.jar
mining_dimension-1.20.1-1.0.4.jar
mob_grinding_utils-1.20.1-1.0.2.jar
molten_vents-1.20.1-2.0.2.jar
moonlight-1.20-2.8.28-forge.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
nocube's_create_compact_exp_1.0.3_forge_1.20.1.jar
Patchouli-1.20.1-81-FORGE.jar
phosphophyllite-1.20.1-0.7.0-alpha.jar
pipez-1.20.1-1.1.5.jar
Placebo-1.20.1-8.3.7.jar
polylib-forge-1200.0.2-build.85.jar
Powah-5.0.2.jar
probejs-5.5.0-forge.jar
productivebees-1.20.1-12.2.1.jar
quartz-1.20.1-0.2.0-alpha.jar
rechiseled-1.1.4-forge-mc1.20.jar
rechiseledcreate-1.0.0a-forge-mc1.20.jar
resourcefulconfig-forge-1.20.1-2.1.0.jar
resourcefullib-forge-1.20.1-2.1.11.jar
rftoolsbase-1.20-5.0.2.jar
rftoolscontrol-1.20-7.0.1.jar
rftoolsdim-1.20-11.0.0.jar
rftoolspower-1.20-6.0.1.jar
rftoolsstorage-1.20-5.0.1.jar
rftoolsutility-1.20-6.0.3.jar
rhino-forge-2001.2.2-build.6.jar
roses-5.0.0.jar
Saros-Create-Addon-1.20.1-1.7-[Forge].jar
ScalableCatsForce-3.3.0-build-2-with-library.jar
Searchables-forge-1.20.1-1.0.1.jar
shetiphiancore-forge-1.20.1-1.1.jar
SkyblockBuilder-1.20.1-5.0.11.jar
SkyBonsais-1.0.1.jar
SkyOrchards-0.0.12.jar
SkyVillages-1.0.2-1.20.1-forge-release.jar
sliceanddice-forge-3.1.2.jar
smallernetherportals-1.20.1-3.4.jar
sophisticatedbackpacks-1.20.1-3.18.59.909.jar
sophisticatedcore-1.20.1-0.5.89.425.jar
squatgrow-forge-5.1.0+mc1.20.1.jar
Steam_Rails-1.5.1+forge-mc1.20.1.jar
storagedrawers-1.20.1-12.0.2.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.12a-forge-mc1.20.jar
SWPlanets-forge-1.20.1-1.0.16.1.jar
TerraBlender-forge-1.20.1-3.0.0.169.jar
theoneprobe-1.20.1-10.0.1.jar
time-in-a-bottle-4.0.4-mc1.20.1.jar
twilightforest-1.20.1-4.3.1850-universal.jar
valkyrienskies-1201-2.3.0-beta.4.jar
VillagerEnchanter-Forge-0.1.jar
waystones-forge-1.20-14.0.2.jar
XaerosWorldMap_1.34.1_Forge_1.20.jar
Xaeros_Minimap_23.8.0_Forge_1.20.jar
xaeros_waystones_compability-1.0.jar

### Additional Context

i'm on 1.20.1  mod version is 1.7.4.d-9 and my forge version is 47.2.0 i get an error when running the start up script to add custom meshes to the sifter

**Comment by oierbravo** [comment]
The  1.7.4.d-9 version for mc 1.20.1 doesn't have kubejs 6.3 integration. If you update to the latest version it should work.
Apart from that... the textures are incorrect, there is no "1" texture. You can specify new textures for `frame`, `mesh` and `particle`.

My recommendation is to follow the README.md as much as you can.
https://github.com/oierbravo/createsifter#adding-custom-meshes-startup-script-1

Plz, close the issue if you manage to resolve it... feel free to ask more questions or issues.

**Comment by billjk2013** [comment]
Would there be a way for me to move the code to a zen script formate that would  work with craft tweaker?

**Comment by oierbravo** [comment]
For creating items you need ContentTweaker and it's not supported.
you have the same error even after updating the mod to the latest version?

I can help you fix the script but I need the script as code to do it.

**Comment by billjk2013** [comment]
I'll create a new instance tonight and update as I also will have to disable some of my other create mods that aren't updated to the newest version of create

**Comment by billjk2013** [comment]
updated it and still getting an error below is a zip of my kubejs folder with scripts
[kubejs.zip](https://github.com/oierbravo/createsifter/files/12755418/kubejs.zip)

**Comment by billjk2013** [comment]
I made some changes based on the code from ftbskies and got it to load now I'm just missing textures this is my new Kubejs folder
[kubejs.zip](https://github.com/oierbravo/createsifter/files/12772035/kubejs.zip)

**Comment by oierbravo** [comment]
Maybe is the namespace. Try putting the textures in assets/kubejs/
```

StartupEvents.registry('item', event => {
	
  event.create('diamond_mesh','createsifter:mesh').displayName('Diamond Mesh').parentModel("createsifter:block/meshes/mesh").texture("mesh","kubejs:item/diamond_mesh");
	event.create('gold_mesh','createsifter:mesh').displayName('Gold Mesh').parentModel("createsifter:block/meshes/custom_mesh").texture("mesh","kubejs:item/gold_mesh");
	event.create('iron_mesh','createsifter:mesh').displayName('Iron Mesh').parentModel("createsifter:block/meshes/custom_mesh").texture("mesh","kubejs:item/iron_mesh");
	event.create('netherite_mesh','createsifter:mesh').displayName('Netherite Mesh').parentModel("createsifter:block/meshes/custom_mesh").texture("mesh","kubejs:item/netherite_mesh");


})
```

For the 1.20.1 the creative tab is missing so you can test it with `/give USERNAME kubejs:diamond_mesh`

**Comment by billjk2013** [comment]
Made the change I think it might be an issue on the kubejs part of things thank you for the help I will be closing the issue

**Comment by billjk2013** [comment]
Alternatively, I'm going to try and make a moch up model and see if that will help fix my texture issue

**Comment by billjk2013** [comment]
I fixed the texture issue I had the parent model wrong 
Was: createsifter:block/meshes/custom_mesh
Changed: createsifter:block/meshes/mesh
Only things is they all look liked an andasite mesh

**Comment by billjk2013** [comment]
The last issue was that I had deleted the reference of "mesh" for the texture section of the code  every thing is loading fine
