### ISSUE TITLE
1.20 branch should be first

### ISSUE THREAD

**Issue by KingTino104** [oierbravo/createsifter#44]
### Describe the Bug

your main branch is set to 1.19

### Reproduction Steps

1. load github
2. goto createsifter github page
3. see the 1.19 branch first instead of 1.20

### Expected Result

see the 1.20 branch first instead of 1.19

### Screenshots and Videos

u can do it urself.

### Crash Report or Log

your mom

### Operating System

google chrome

### Mod Version

1.20.1-1.8.1.e-22

### Minecraft Version

1.20.1

### Forge Version

69.0.0

### Other Mods

im not telling u my chrome extensions

**Comment by oierbravo** [comment]
1.19 for now it's my main branch. I like it like this. I will change it when Create drops support for 1.18.2
