### ISSUE TITLE
Kubejs issue

### ISSUE THREAD

**Issue by MisterZam27** [oierbravo/createsifter#67]
### Describe the Bug

I followed along the recipe for Kubejs 6.1 but for some reason it does not create it.

 event.recipes.createsifter.sifting([
  item.of('minecraft:iron_nugget').withChance(0.3),
  item.of('create:copper_nugget').withChance(0.4),
  item.of('create:zinc_nugget').withChance(0.4)
], ['minecraft:gravel', 'createsifter:string_mesh']).waterlogged()

I tried createsifterShifting still the same

btw codeblock 19 is where the waterlogged() is

### Reproduction Steps

1. install latest kubejs and kubejs create together with create sifter mod
2. run the code
3.
...

### Expected Result

creates a recipe based from the code

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/d1486309-4815-4262-91e8-8adc02d7b4af)

### Operating System

windows 10

### Mod Version

1.20.1-1.8.1.e-22

### Minecraft Version

1.20.1

### Forge Version

Neoforge 47.1.106

**Comment by MisterZam27** [comment]
event.recipes.createsifter.sifting({
  type: 'createsifter:sifting',
  ingredients: [{item: 'minecraft:gravel'}, {item: 'createsifter:string_mesh'}],
  results: [
    {item: 'minecraft:iron_nugget', chance: 0.3},
    {item: 'create:copper_nugget', chance: 0.4},
    {item: 'create:zinc_nugget', chance: 0.4}
  ], waterlogged: true
})

resorted to using .json welp

**Comment by Normal69** [comment]
> ### Operating System
> 
> windows 10
> ### Mod Version
> 
> 1.20.1-1.8.1.e-22
> ### Minecraft Version
> 
> 1.20.1
> ### Forge Version
> 
> Neoforge 47.1.106
> ### Other Mods

Pardon me, but I need to run exactly this version on MC, but it says I need forge.
Would you kindly tell me the solution?
