### ISSUE TITLE
[Suggestion] Add support for input by TAG and Waterlogged sifting

### ISSUE THREAD

**Issue by AerosAtar** [oierbravo/createsifter#7]
- Add ability to register input by tag. (example: #minecraft:sand)
- Add ability for sifter to be waterlogged.
  - Add ability to register waterlogged as a requirement for a recipe and/or output.

These would be required for any ExNihilo compatibility, which you have mentioned you want to look into doing on the curseforge page.

**Comment by oierbravo** [comment]
Hi!
Thanks for taking the time to post it here.
Both suggestions are in the to do list ;)
